services:
  mysql-db:
    image: mysql:5.7  # MySQL 5.7 버전으로 설정합니다.
    platform: linux/amd64  # amd64 플랫폼으로 설정합니다.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onion1!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user  # 추가 사용자 이름입니다.
      MYSQL_PASSWORD: onion1!
    ports:
      - "3306:3306"  # 로컬 포트 3306을 컨테이너의 포트 3306에 매핑합니다.
    volumes:
      - db_data:/var/lib/mysql  # MySQL 데이터를 호스트에 영구 저장합니다.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=onion1!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    command: >
      sh -c "
      bin/elasticsearch-plugin install analysis-nori;
      bin/elasticsearch
      "
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
      - LOGSTASH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/mysql-connector-j-9.0.0.jar:/usr/share/logstash/mysql-connector-j-9.0.0.jar
    ports:
      - "5044:5044"
      - "9600:9600"  # Logstash monitoring API

  mongodb:
    image: mongo:7
    restart: always
    # 인증을 사용하고 싶으시면 아래 두 줄을 활성화하세요.
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: onion1!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  es-data:
    driver: local
  mongo_data:

